# Fichier de configuration "Blueprint" pour Render
# Il définit tous les services nécessaires pour l'application.

services:
  # 1. Service pour la base de données PostgreSQL
  - type: postgresql # <-- CORRECTION ICI
    name: caisse-db
    databaseName: caisse_eglise_db
    plan: free # Utilise le plan gratuit

  # 2. Service pour le serveur backend Node.js
  - type: web
    name: caisse-backend
    env: node
    plan: free # Utilise le plan gratuit
    # Indique à Render où trouver le code du backend
    rootDir: ./backend
    buildCommand: npm install
    startCommand: node server.js
    # Connecte automatiquement le serveur à la base de données
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: caisse-db
          property: connectionString